# Generated by Django 2.1.7 on 2019-03-20 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interface_app', '0007_auto_20181214_2211'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testcase',
            options={'verbose_name': '测试用例', 'verbose_name_plural': '测试用例'},
        ),
        migrations.AlterModelOptions(
            name='testresult',
            options={'verbose_name': '测试结果', 'verbose_name_plural': '测试结果'},
        ),
        migrations.AlterModelOptions(
            name='testtask',
            options={'verbose_name': '测试任务', 'verbose_name_plural': '测试任务'},
        ),
    ]
